version: '3.1'

services:

  db:
    image: postgres:12.11-alpine3.16
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
